// Code generated by swaggo/swag — regenerate with: make swagger
package docs

import "github.com/swaggo/swag"

// SwaggerInfo is exported so callers can override Host/BasePath at runtime.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Healthcare API",
	Description:      "Healthcare Management System REST API.\n\nAll protected endpoints require `Authorization: Bearer <accessToken>`.\n\nObtain tokens via POST /auth/login.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}

const docTemplate = `{
  "swagger": "2.0",
  "info": {
    "description": "Healthcare Management System REST API. All protected endpoints require Authorization: Bearer token.",
    "title": "Healthcare API",
    "contact": {"name": "Healthcare API Support"},
    "version": "1.0"
  },
  "host": "localhost:8080",
  "basePath": "/",
  "schemes": ["http", "https"],
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "securityDefinitions": {
    "BearerAuth": {
      "type": "apiKey",
      "description": "Enter: Bearer {your_access_token}",
      "name": "Authorization",
      "in": "header"
    }
  },
  "paths": {
    "/auth/login": {
      "post": {
        "description": "Authenticate with email and password. Returns access token in body; refresh token is set as httpOnly cookie.",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "tags": ["Authentication"],
        "summary": "User login",
        "parameters": [{"description": "Login credentials", "name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/LoginRequest"}}],
        "responses": {
          "200": {"description": "Success — access token + user info", "schema": {"$ref": "#/definitions/LoginResponse"}},
          "400": {"description": "Invalid request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
          "401": {"description": "Invalid credentials", "schema": {"$ref": "#/definitions/ErrorResponse"}},
          "429": {"description": "Rate limited", "schema": {"$ref": "#/definitions/ErrorResponse"}}
        }
      }
    },
    "/auth/register": {
      "post": {
        "security": [{"BearerAuth": []}],
        "description": "Create a new user account. Requires admin role.",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "tags": ["Authentication"],
        "summary": "Register user (Admin only)",
        "parameters": [{"description": "Registration data", "name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/RegisterRequest"}}],
        "responses": {
          "201": {"description": "User created", "schema": {"$ref": "#/definitions/UserDTO"}},
          "400": {"description": "Invalid input", "schema": {"$ref": "#/definitions/ErrorResponse"}},
          "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
          "403": {"description": "Admin only", "schema": {"$ref": "#/definitions/ErrorResponse"}}
        }
      }
    },
    "/auth/refresh": {
      "post": {
        "description": "Exchange valid refresh token (httpOnly cookie or body) for a new access token. Refresh token is rotated.",
        "produces": ["application/json"],
        "tags": ["Authentication"],
        "summary": "Refresh access token",
        "responses": {
          "200": {"description": "New access token", "schema": {"$ref": "#/definitions/LoginResponse"}},
          "401": {"description": "Invalid or expired token", "schema": {"$ref": "#/definitions/ErrorResponse"}}
        }
      }
    },
    "/auth/logout": {
      "post": {
        "security": [{"BearerAuth": []}],
        "description": "Blacklist current access token JTI and revoke all refresh tokens.",
        "produces": ["application/json"],
        "tags": ["Authentication"],
        "summary": "Logout",
        "responses": {
          "200": {"description": "Logged out"},
          "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}}
        }
      }
    },
    "/patients": {
      "get": {
        "security": [{"BearerAuth": []}],
        "description": "Paginated patient list. Registrar and Admin only.",
        "produces": ["application/json"],
        "tags": ["Patients"],
        "summary": "List patients",
        "parameters": [
          {"name": "page", "in": "query", "type": "integer", "default": 1},
          {"name": "pageSize", "in": "query", "type": "integer", "default": 50}
        ],
        "responses": {
          "200": {"description": "Patient list", "schema": {"type": "array", "items": {"$ref": "#/definitions/PatientDTO"}}},
          "401": {"description": "Unauthorized"},
          "403": {"description": "Forbidden"}
        }
      },
      "post": {
        "security": [{"BearerAuth": []}],
        "description": "Register a new patient. Registrar and Admin only.",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "tags": ["Patients"],
        "summary": "Register patient",
        "parameters": [{"description": "Patient data", "name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/CreatePatientRequest"}}],
        "responses": {
          "201": {"description": "Patient created", "schema": {"$ref": "#/definitions/PatientDTO"}},
          "400": {"description": "Invalid input", "schema": {"$ref": "#/definitions/ErrorResponse"}},
          "401": {"description": "Unauthorized"},
          "403": {"description": "Forbidden"}
        }
      }
    },
    "/patients/{id}": {
      "get": {
        "security": [{"BearerAuth": []}],
        "description": "Get patient by ID. Doctors can only view patients they have appointments with.",
        "produces": ["application/json"],
        "tags": ["Patients"],
        "summary": "Get patient",
        "parameters": [{"name": "id", "in": "path", "required": true, "type": "integer"}],
        "responses": {
          "200": {"description": "Patient data", "schema": {"$ref": "#/definitions/PatientDTO"}},
          "401": {"description": "Unauthorized"},
          "403": {"description": "Forbidden"},
          "404": {"description": "Not found"}
        }
      }
    },
    "/appointments": {
      "get": {
        "security": [{"BearerAuth": []}],
        "description": "List appointments. Doctors see only their own; admins and registrars see all.",
        "produces": ["application/json"],
        "tags": ["Appointments"],
        "summary": "List appointments",
        "parameters": [
          {"name": "page", "in": "query", "type": "integer", "default": 1},
          {"name": "pageSize", "in": "query", "type": "integer", "default": 50}
        ],
        "responses": {
          "200": {"description": "Appointment list", "schema": {"type": "array", "items": {"$ref": "#/definitions/AppointmentDTO"}}},
          "401": {"description": "Unauthorized"}
        }
      },
      "post": {
        "security": [{"BearerAuth": []}],
        "description": "Schedule a new appointment. Registrar and Admin only.",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "tags": ["Appointments"],
        "summary": "Create appointment",
        "parameters": [{"description": "Appointment data", "name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/CreateAppointmentRequest"}}],
        "responses": {
          "201": {"description": "Appointment created", "schema": {"$ref": "#/definitions/AppointmentDTO"}},
          "400": {"description": "Invalid input"},
          "401": {"description": "Unauthorized"},
          "403": {"description": "Forbidden"}
        }
      }
    },
    "/treatments": {
      "post": {
        "security": [{"BearerAuth": []}],
        "description": "Add treatment to an appointment. Doctor only; must be the assigned doctor.",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "tags": ["Treatments"],
        "summary": "Add treatment",
        "parameters": [{"description": "Treatment data", "name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/CreateTreatmentRequest"}}],
        "responses": {
          "201": {"description": "Treatment created", "schema": {"$ref": "#/definitions/TreatmentDTO"}},
          "400": {"description": "Invalid input"},
          "401": {"description": "Unauthorized"},
          "403": {"description": "Forbidden — not assigned to this appointment"}
        }
      }
    },
    "/reports/{id}": {
      "get": {
        "security": [{"BearerAuth": []}],
        "description": "Get appointment report with treatment details. Doctor (own appointments) or Admin.",
        "produces": ["application/json"],
        "tags": ["Reports"],
        "summary": "Get report",
        "parameters": [{"name": "id", "in": "path", "required": true, "type": "integer", "description": "Appointment ID"}],
        "responses": {
          "200": {"description": "Report data", "schema": {"$ref": "#/definitions/ReportDTO"}},
          "401": {"description": "Unauthorized"},
          "403": {"description": "Forbidden"},
          "404": {"description": "Not found or no treatment recorded"}
        }
      }
    },
    "/audit-logs/{id}": {
      "get": {
        "security": [{"BearerAuth": []}],
        "description": "Get audit logs for a specific patient. Admin only.",
        "produces": ["application/json"],
        "tags": ["Audit"],
        "summary": "Get audit logs",
        "parameters": [{"name": "id", "in": "path", "required": true, "type": "integer", "description": "Patient ID"}],
        "responses": {
          "200": {"description": "Audit log list"},
          "401": {"description": "Unauthorized"},
          "403": {"description": "Admin only"}
        }
      }
    },
    "/health": {
      "get": {
        "description": "Returns 200 if the service is running.",
        "produces": ["application/json"],
        "tags": ["System"],
        "summary": "Health check",
        "responses": {
          "200": {"description": "Healthy"}
        }
      }
    }
  },
  "definitions": {
    "LoginRequest": {
      "type": "object",
      "required": ["email", "password"],
      "properties": {
        "email":    {"type": "string", "example": "admin@healthcare.local"},
        "password": {"type": "string", "example": "Admin@123456"}
      }
    },
    "LoginResponse": {
      "type": "object",
      "properties": {
        "accessToken": {"type": "string"},
        "expiresAt":   {"type": "string", "format": "date-time"},
        "user":        {"$ref": "#/definitions/UserDTO"}
      }
    },
    "RegisterRequest": {
      "type": "object",
      "required": ["email","password","firstName","lastName","role"],
      "properties": {
        "email":     {"type": "string"},
        "password":  {"type": "string", "minLength": 8},
        "firstName": {"type": "string"},
        "lastName":  {"type": "string"},
        "role":      {"type": "string", "enum": ["admin","registrar","doctor"]}
      }
    },
    "UserDTO": {
      "type": "object",
      "properties": {
        "id":        {"type": "integer"},
        "email":     {"type": "string"},
        "firstName": {"type": "string"},
        "lastName":  {"type": "string"},
        "role":      {"type": "string"}
      }
    },
    "CreatePatientRequest": {
      "type": "object",
      "required": ["firstName","lastName","email","dateOfBirth","gender"],
      "properties": {
        "firstName":   {"type": "string", "maxLength": 100},
        "lastName":    {"type": "string", "maxLength": 100},
        "email":       {"type": "string", "format": "email"},
        "phone":       {"type": "string", "example": "+12025551234", "description": "E.164 format"},
        "dateOfBirth": {"type": "string", "example": "1990-01-15", "description": "YYYY-MM-DD"},
        "gender":      {"type": "string", "enum": ["M","F","O"]},
        "address":     {"type": "string"},
        "medicalInfo": {"type": "string"}
      }
    },
    "PatientDTO": {
      "type": "object",
      "properties": {
        "id":           {"type": "integer"},
        "firstName":    {"type": "string"},
        "lastName":     {"type": "string"},
        "email":        {"type": "string"},
        "phone":        {"type": "string"},
        "dateOfBirth":  {"type": "string", "format": "date-time"},
        "gender":       {"type": "string"},
        "address":      {"type": "string"},
        "medicalInfo":  {"type": "string"},
        "registeredBy": {"type": "integer"},
        "createdAt":    {"type": "string", "format": "date-time"},
        "updatedAt":    {"type": "string", "format": "date-time"}
      }
    },
    "CreateAppointmentRequest": {
      "type": "object",
      "required": ["patientId","doctorId","scheduledAt","reason"],
      "properties": {
        "patientId":   {"type": "integer"},
        "doctorId":    {"type": "integer"},
        "scheduledAt": {"type": "string", "example": "2026-06-15T10:00:00Z"},
        "reason":      {"type": "string", "maxLength": 500}
      }
    },
    "AppointmentDTO": {
      "type": "object",
      "properties": {
        "id":          {"type": "integer"},
        "patientId":   {"type": "integer"},
        "doctorId":    {"type": "integer"},
        "scheduledAt": {"type": "string", "format": "date-time"},
        "reason":      {"type": "string"},
        "status":      {"type": "string", "enum": ["pending","completed","cancelled"]},
        "notes":       {"type": "string"},
        "createdAt":   {"type": "string", "format": "date-time"},
        "updatedAt":   {"type": "string", "format": "date-time"}
      }
    },
    "CreateTreatmentRequest": {
      "type": "object",
      "required": ["appointmentId","diagnosis"],
      "properties": {
        "appointmentId": {"type": "integer"},
        "diagnosis":     {"type": "string", "maxLength": 1000},
        "prescription":  {"type": "string", "maxLength": 1000},
        "notes":         {"type": "string"}
      }
    },
    "TreatmentDTO": {
      "type": "object",
      "properties": {
        "id":            {"type": "integer"},
        "appointmentId": {"type": "integer"},
        "patientId":     {"type": "integer"},
        "doctorId":      {"type": "integer"},
        "diagnosis":     {"type": "string"},
        "prescription":  {"type": "string"},
        "notes":         {"type": "string"},
        "createdAt":     {"type": "string", "format": "date-time"},
        "updatedAt":     {"type": "string", "format": "date-time"}
      }
    },
    "ReportDTO": {
      "type": "object",
      "properties": {
        "id":            {"type": "integer"},
        "appointmentId": {"type": "integer"},
        "patientId":     {"type": "integer"},
        "doctorId":      {"type": "integer"},
        "diagnosis":     {"type": "string"},
        "prescription":  {"type": "string"},
        "notes":         {"type": "string"},
        "generatedAt":   {"type": "string", "format": "date-time"}
      }
    },
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "code":    {"type": "string"},
        "message": {"type": "string"}
      }
    }
  }
}`
